---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
    name: alter-test-app-ingress
    annotations:
        kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: alter-test.chuprunov.name
      http:
        paths:
        - backend:
            serviceName: alter-test-app
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alter-test-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: alter-test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alter-test-app
spec:
  selector:
    matchLabels:
      app: alter-test-app
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: alter-test-app
    spec:
      containers:
      - name: alter-test-app
        image: unitedt/alter-test-app:latest
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: "${DATABASE_URL}"
        ports:
        - containerPort: 8080
          protocol: TCP
